Resources:
  VaccineAlertTopic357C4830:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: VaccineAlertTopic
    Metadata:
      aws:cdk:path: VaccineAlertStack/VaccineAlertTopic/Resource
  VaccineAlertTopicTokenSubscription1C83C1758:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sms
      TopicArn:
        Ref: VaccineAlertTopic357C4830
      Endpoint:
        Fn::Join:
          - ""
          - - "+1"
            - Ref: phoneNumber
    Metadata:
      aws:cdk:path: VaccineAlertStack/VaccineAlertTopic/TokenSubscription:1/Resource
  FoundTerms831C4958:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: url
          KeyType: HASH
        - AttributeName: term
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S
        - AttributeName: term
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: FoundItems
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: VaccineAlertStack/FoundTerms/Resource
  VaccineMonitorHandlerServiceRole5F850586:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: VaccineAlertStack/VaccineMonitorHandler/ServiceRole/Resource
  VaccineMonitorHandlerServiceRoleDefaultPolicy072015DA:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sns:Publish
            Effect: Allow
            Resource:
              Ref: VaccineAlertTopic357C4830
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:ConditionCheckItem
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - FoundTerms831C4958
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: VaccineMonitorHandlerServiceRoleDefaultPolicy072015DA
      Roles:
        - Ref: VaccineMonitorHandlerServiceRole5F850586
    Metadata:
      aws:cdk:path: VaccineAlertStack/VaccineMonitorHandler/ServiceRole/DefaultPolicy/Resource
  VaccineMonitorHandler808411A2:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters0adbe6b58a4158dd81fd26b3c0ed3e1871925a6fa23dc7ddabdc1b9d02f4bc3eS3Bucket748FDBCC
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters0adbe6b58a4158dd81fd26b3c0ed3e1871925a6fa23dc7ddabdc1b9d02f4bc3eS3VersionKey36A376C2
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters0adbe6b58a4158dd81fd26b3c0ed3e1871925a6fa23dc7ddabdc1b9d02f4bc3eS3VersionKey36A376C2
      Role:
        Fn::GetAtt:
          - VaccineMonitorHandlerServiceRole5F850586
          - Arn
      Environment:
        Variables:
          ALERT_TOPIC_ARN:
            Ref: VaccineAlertTopic357C4830
          FOUND_TERMS_TABLE_NAME:
            Ref: FoundTerms831C4958
      FunctionName: VaccineMonitorHandler
      Handler: vaccine-monitor.handler
      Runtime: nodejs14.x
      Timeout: 10
    DependsOn:
      - VaccineMonitorHandlerServiceRoleDefaultPolicy072015DA
      - VaccineMonitorHandlerServiceRole5F850586
    Metadata:
      aws:cdk:path: VaccineAlertStack/VaccineMonitorHandler/Resource
      aws:asset:path: /Users/bretth/Develop/bhoven/vaccine-volunteer-alert/src
      aws:asset:property: Code
  VaccineMonitorHandlerAllowEventRuleVaccineAlertStackMonitorScheduleRuleB4F50D5D1DA96626:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - VaccineMonitorHandler808411A2
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - MonitorScheduleRule509A3CB8
          - Arn
    Metadata:
      aws:cdk:path: VaccineAlertStack/VaccineMonitorHandler/AllowEventRuleVaccineAlertStackMonitorScheduleRuleB4F50D5D
  MonitorScheduleRule509A3CB8:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(*/15 * * * ? *)
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - VaccineMonitorHandler808411A2
              - Arn
          Id: Target0
    Metadata:
      aws:cdk:path: VaccineAlertStack/MonitorScheduleRule/Resource
  MonitorFailureAlarm9C6557B4:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      AlarmActions:
        - Ref: VaccineAlertTopic357C4830
      AlarmName: MonitorFailureAlarm
      Dimensions:
        - Name: FunctionName
          Value:
            Ref: VaccineMonitorHandler808411A2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 300
      Statistic: Sum
      Threshold: 1
    Metadata:
      aws:cdk:path: VaccineAlertStack/MonitorFailureAlarm/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.89.0,@aws-cdk/assets=1.90.0,@aws-cdk/aws-applicationautoscaling=1.90.0,@aws-cdk/aws-autoscaling=1.90.0,@aws-cdk/aws-autoscaling-common=1.90.0,@aws-cdk/aws-autoscaling-hooktargets=1.90.0,@aws-cdk/aws-cloudwatch=1.90.0,@aws-cdk/aws-cloudwatch-actions=1.90.0,@aws-cdk/aws-codeguruprofiler=1.90.0,@aws-cdk/aws-dynamodb=1.90.0,@aws-cdk/aws-ec2=1.90.0,@aws-cdk/aws-ecr=1.90.0,@aws-cdk/aws-ecr-assets=1.90.0,@aws-cdk/aws-ecs=1.90.0,@aws-cdk/aws-elasticloadbalancingv2=1.90.0,@aws-cdk/aws-events=1.90.0,@aws-cdk/aws-events-targets=1.90.0,@aws-cdk/aws-iam=1.90.0,@aws-cdk/aws-kms=1.90.0,@aws-cdk/aws-lambda=1.90.0,@aws-cdk/aws-logs=1.90.0,@aws-cdk/aws-s3=1.90.0,@aws-cdk/aws-s3-assets=1.90.0,@aws-cdk/aws-servicediscovery=1.90.0,@aws-cdk/aws-sns=1.90.0,@aws-cdk/aws-sns-subscriptions=1.90.0,@aws-cdk/aws-sqs=1.90.0,@aws-cdk/aws-ssm=1.90.0,@aws-cdk/cloud-assembly-schema=1.90.0,@aws-cdk/core=1.90.0,@aws-cdk/custom-resources=1.90.0,@aws-cdk/cx-api=1.90.0,@aws-cdk/region-info=1.90.0,jsii-runtime=node.js/v14.15.5
    Metadata:
      aws:cdk:path: VaccineAlertStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  phoneNumber:
    Type: String
    Description: Phone number which will receive alerts via SMS
  AssetParameters0adbe6b58a4158dd81fd26b3c0ed3e1871925a6fa23dc7ddabdc1b9d02f4bc3eS3Bucket748FDBCC:
    Type: String
    Description: S3 bucket for asset "0adbe6b58a4158dd81fd26b3c0ed3e1871925a6fa23dc7ddabdc1b9d02f4bc3e"
  AssetParameters0adbe6b58a4158dd81fd26b3c0ed3e1871925a6fa23dc7ddabdc1b9d02f4bc3eS3VersionKey36A376C2:
    Type: String
    Description: S3 key for asset version "0adbe6b58a4158dd81fd26b3c0ed3e1871925a6fa23dc7ddabdc1b9d02f4bc3e"
  AssetParameters0adbe6b58a4158dd81fd26b3c0ed3e1871925a6fa23dc7ddabdc1b9d02f4bc3eArtifactHash2D34C956:
    Type: String
    Description: Artifact hash for asset "0adbe6b58a4158dd81fd26b3c0ed3e1871925a6fa23dc7ddabdc1b9d02f4bc3e"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

